WEB_CONFIG_FILE = "config/web_config.json"
USER_AGENTS_FILE = "config/user_agents.json"
APK_FILE_LOCAL = "\\resources\\Android-NativeDemoApp-0.4.0.apk"
APK_FILE_REMOTE = "storage:filename=Android-NativeDemoApp-0.4.0.apk"
DEVICE_NAME_LOCAL = "Pixel_3a_API_33_x86_64"
DEVICE_NAME_REMOTE = "Android GoogleAPI Emulator"
